const $=id=>document.getElementById(id);let exams=[],generated=null,analysisRows=[],analysisExam=null,allExamData=null;
async function init(){allExamData=await fetch('data/exams.json').then(r=>r.json());exams=allExamData.exams||[];$('analysisExam').innerHTML=exams.map(e=>`<option value="${e.id}">${e.title}</option>`).join('');bind();}
function bind(){
 $('adminLoginBtn').onclick=adminLogin;$('adminLogoutBtn').onclick=()=>{$('adminApp').classList.add('hidden');$('adminGate').classList.remove('hidden')};document.querySelectorAll('.menuBtn').forEach(b=>b.onclick=()=>showSection(b.dataset.target));
 $('generateCodesBtn').onclick=generateCodes;$('downloadUsersBtn').onclick=downloadUsers;$('downloadSecretsBtn').onclick=downloadSecrets;$('printSlipsBtn').onclick=()=>window.print();$('readPdfBtn').onclick=readPdf;$('saveDraftExamBtn').onclick=saveDraft;$('analyzeBtn').onclick=analyzeFile;$('classFilter').onchange=renderAnalysis;$('exportExamDataBtn').onclick=exportExamData;
}
async function adminLogin(){const pass=$('adminPass').value;if(pass.length<8){$('adminMsg').className='error small';$('adminMsg').textContent='8文字以上で入力してください。';return}const h=await TDX.sha256Hex(pass),saved=localStorage.getItem('tdxAdminHash');if(!saved){localStorage.setItem('tdxAdminHash',h);$('adminMsg').className='success small';$('adminMsg').textContent='この端末に管理用パスワードを登録しました。';}else if(saved!==h){$('adminMsg').className='error small';$('adminMsg').textContent='管理用パスワードが違います。';return}$('adminGate').classList.add('hidden');$('adminApp').classList.remove('hidden');showSection('studentManager')}
function showSection(id){document.querySelectorAll('.adminSection').forEach(x=>x.classList.toggle('hidden',x.id!==id))}
async function generateCodes(){const codes=[...new Set($('studentCodes').value.split(/\s+/).map(s=>s.trim()).filter(Boolean))];if(!codes.length||codes.some(c=>!/^\d{4}$/.test(c))){alert('4桁番号を1行に1人ずつ入力してください。');return}const digits=Number($('classDigits').value)||2;const users=[],secrets=[];for(const studentCode of codes){const raw=TDX.randomCode(12),pretty=`${raw.slice(0,4)}-${raw.slice(4,8)}-${raw.slice(8)}`,v=await TDX.makeVerifier(pretty);users.push({studentCode,salt:v.salt,hash:v.hash,classKey:studentCode.slice(0,digits)});secrets.push({studentCode,accessCode:pretty,classKey:studentCode.slice(0,digits)})}generated={users,secrets};$('downloadUsersBtn').disabled=false;$('downloadSecretsBtn').disabled=false;$('printSlipsBtn').disabled=false;renderGenerated()}
function renderGenerated(){const rows=generated.secrets.slice(0,12).map(x=>`<tr><td>${x.studentCode}</td><td><code>${x.accessCode}</code></td><td>${x.classKey}</td></tr>`).join('');$('generatedPreview').innerHTML=`<h3>生成結果（先頭12人）</h3><table><thead><tr><th>4桁番号</th><th>ログインコード</th><th>クラス</th></tr></thead><tbody>${rows}</tbody></table>`;$('slips').innerHTML=generated.secrets.map((x,i)=>`<section class="slip"><h2>T-DX Lab☆問題演習システム</h2><p>あなた専用のログイン票です。ほかの人に見せないでください。</p><p>4桁番号</p><div class="code">${x.studentCode}</div><p>専用ログインコード</p><div class="code">${x.accessCode}</div><p class="small">学校アカウント等で使用しているパスワードとは別の、このシステム専用コードです。</p><div class="cutline"></div></section>`).join('')}
function downloadUsers(){TDX.download('users.json',JSON.stringify({version:1,users:generated.users},null,2))}
function downloadSecrets(){const csv='4桁番号,ログインコード,クラス\n'+generated.secrets.map(x=>`${x.studentCode},${x.accessCode},${x.classKey}`).join('\n');TDX.download('T-DX_Lab_ログインコード教員保管.csv','\ufeff'+csv,'text/csv;charset=utf-8')}
async function readPdf(){const f=$('answerPdf').files[0];if(!f){alert('PDFを選択してください。');return}try{const buf=await f.arrayBuffer();const pdfjs=await import('https://cdnjs.cloudflare.com/ajax/libs/pdf.js/4.8.69/pdf.min.mjs');pdfjs.GlobalWorkerOptions.workerSrc='https://cdnjs.cloudflare.com/ajax/libs/pdf.js/4.8.69/pdf.worker.min.mjs';const pdf=await pdfjs.getDocument({data:buf}).promise;let text='';for(let p=1;p<=pdf.numPages;p++){const page=await pdf.getPage(p),tc=await page.getTextContent();text+=`\n--- page ${p} ---\n`+tc.items.map(x=>x.str).join(' ')}$('pdfText').value=text.trim()}catch(e){alert('PDF読み取りに失敗しました。ネットワーク環境を確認してください。') }}
function saveDraft(){const draft={title:$('examName').value.trim(),subject:$('examSubjectInput').value.trim(),googleFormUrl:$('formUrl').value.trim(),pdfText:$('pdfText').value.trim(),createdAt:new Date().toISOString()};if(!draft.title||!draft.subject){$('draftExamMsg').className='error small';$('draftExamMsg').textContent='試験名と教科を入力してください。';return}localStorage.setItem('tdxDraftExam',JSON.stringify(draft));$('draftExamMsg').className='success small';$('draftExamMsg').textContent='下書きをこのブラウザに保存しました。次段階で正答・配点確認画面につなげます。'}
async function readRows(file){if(/\.csv$/i.test(file.name)){return TDX.csvParse(await file.text())}const buf=await file.arrayBuffer(),wb=XLSX.read(buf,{type:'array'}),ws=wb.Sheets[wb.SheetNames[0]];return XLSX.utils.sheet_to_json(ws,{header:1,raw:false,defval:''})}
async function analyzeFile(){const f=$('responseFile').files[0];if(!f){alert('CSVまたはXLSXを選択してください。');return}analysisExam=exams.find(e=>e.id===$('analysisExam').value);const rows=await readRows(f);if(rows.length<2){alert('回答データが見つかりません。');return}const header=rows[0],qCount=analysisExam.questions.length;analysisRows=[];for(const r of rows.slice(1)){const code=String(r[2]||'').trim();if(!/^\d{4}$/.test(code))continue;const ansVals=r.slice(r.length-qCount);const answers={};analysisExam.questions.forEach((q,i)=>answers[q.id]=String(ansVals[i]??'').trim());const score=TDX.scoreExam(analysisExam,answers);analysisRows.push({code,classKey:code.slice(0,Number($('classDigits').value)||2),answers,score})}if(!analysisRows.length){alert('4桁番号を含む回答行を認識できませんでした。');return}const classes=[...new Set(analysisRows.map(r=>r.classKey))].sort();$('classFilter').innerHTML='<option value="ALL">全クラス</option>'+classes.map(c=>`<option value="${c}">${c}</option>`).join('');$('analysisOutput').classList.remove('hidden');renderAnalysis()}
function renderAnalysis(){if(!analysisRows.length)return;const key=$('classFilter').value,rows=key==='ALL'?analysisRows:analysisRows.filter(r=>r.classKey===key),scores=rows.map(r=>r.score.total),avg=scores.reduce((a,b)=>a+b,0)/scores.length,max=Math.max(...scores),min=Math.min(...scores);$('analysisKpis').innerHTML=`<div class="kpi"><div class="muted small">回答者</div><div class="value">${rows.length}</div></div><div class="kpi"><div class="muted small">平均点</div><div class="value">${avg.toFixed(1)}</div></div><div class="kpi"><div class="muted small">最高点</div><div class="value">${max}</div></div><div class="kpi"><div class="muted small">最低点</div><div class="value">${min}</div></div>`;renderHistogram(scores);renderSections(rows);renderQuestionRates(rows)}
function renderHistogram(scores){const bins=Array(10).fill(0);scores.forEach(s=>bins[Math.min(9,Math.floor(s/10))]++);const m=Math.max(...bins,1);$('histogram').innerHTML=bins.map((n,i)=>`<div class="col"><div class="stick" style="height:${Math.max(2,n/m*180)}px" title="${n}人"></div><div class="lab">${i*10}-${i===9?100:i*10+9}<br>${n}人</div></div>`).join('')}
function renderSections(rows){$('sectionAnalysis').innerHTML=analysisExam.sections.map(s=>{const sum=rows.reduce((a,r)=>a+(r.score.sectionScores[s.id]||0),0),pct=sum/(rows.length*s.points)*100;return `<div class="bar-row"><strong>${s.name}</strong><div class="bar"><div style="width:${pct.toFixed(1)}%"></div></div><div>${pct.toFixed(1)}%</div></div>`}).join('')}
function renderQuestionRates(rows){const body=$('questionRates');body.innerHTML='';analysisExam.questions.forEach(q=>{let ok=0;rows.forEach(r=>{const d=r.score.detail.find(x=>x.q.id===q.id);if(d&&d.correct)ok++});const pct=ok/rows.length*100;body.insertAdjacentHTML('beforeend',`<tr><td>${q.label}</td><td>${pct.toFixed(1)}%</td><td>${ok}/${rows.length}</td></tr>`)});}
function exportExamData(){TDX.download('exams.json',JSON.stringify(allExamData,null,2))}
init().catch(console.error);
